### ISSUE TITLE
undeclared identifier: 'IndexDefect'

### ISSUE THREAD

**Issue by wokibe** [oliversandli/clapfn#1]
clapfn.nim does not compile:
src/clapfn.nim(209, 14) Error: undeclared identifier: 'IndexDefect'

replacing IndexDefect by IndexError solves the issue

**Comment by oliverdelancey** [comment]
I changed IndexError to IndexDefect due to a deprecation warning. (See [https://github.com/nim-lang/Nim/pull/13908](https://github.com/nim-lang/Nim/pull/13908))

What version of Nim are you using?

**Comment by wokibe** [comment]
Hi Oliver,

I have "found" Nim just about 2 weeks ago. I tried;
curl https://nim-lang.org/choosenim/init.sh -sSf | sh
but it failed, because choosenim requires macOs 10.13, but the last version
available for my old (2010) IMac is 10.12.4:

So I build it on Oct/15 from the downloaded source tar ball from
nim-lang.org:

(MyTest) WolfgangersiMac:01 kittekat$ nim -v

Nim Compiler Version 1.2.6 [MacOSX: amd64]

Compiled at 2020-10-15

Copyright (c) 2006-2020 by Andreas Rumpf

Today nim-lang.org offers nim 1.4.0. The release date is Oct/16 - so I
missed it by just one day.

Sorry for the open of this issue. I googled for IndexDefect vs IndexError
but did not find anything usable.

Anyway, I like clapfn for it's similarity to Pythons ArgumentParser. You
did a great job!

Best regards
Wolfgang Kittenberger
.

**Comment by oliverdelancey** [comment]
Hey Wolfgang,

`I have "found" Nim just about 2 weeks ago.` Awesome! Nim is really fun, and the design philosophies are great.

`Sorry for the open of this issue. I googled for IndexDefect vs IndexError
but did not find anything usable.` 
No problem! I'll look into making `clapfn` more compatible with older versions of Nim. I always keep as up-to-date as possible, which has the downside of occasionally breaking my code as I add the latest features.

Is `clapfn` working for you now? If not, I'll move fixing the new IndexDefect problem higher up on my to-do list.

And thank you for the complement! I really appreciate it. It's nice to hear back from people using my code.

Oliver

**Comment by wokibe** [comment]
Hi Oliver,

clapfn is working for me, as I installed a local "corrected" zip copy of
your repository.
I will try to install Nim 1.4.0 soon.

My personal history in programming started about 50 years ago with Fortran
(as being educated as physicist). Then followed by
several assemblers, Cobol(aweful), Pascal, SPL, Delphi, Ruby and Python. I
tried Java(terrible), failed 3 times learning Haskell,
and experimented with Kotlin, Rust and Julia.

So you can eventually imagine my enthusiasmus for Nim. For me it is a
hidden jewel which deserves much more appreciation.

Wolfgang

**Comment by oliverdelancey** [comment]
Hi Wolfgang,

I'm glad you got it working. I will probably add a declaration check for backwards compatibility. 
```nim
when not declared(IndexDefect):
  # IndexDefect = IndexError
```

Oliver
